# .github/workflows/flutter.yml

name: 🔧 Flutter CI

on:
  push:
    branches:
      - test/workflow
      - main
      - develop
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - "*"

jobs:
  analyze:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📶 Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: 📅 Cache Flutter pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: 📁 Install dependencies
        run: flutter pub get

      - name: 📊 Analyze code
        run: flutter analyze

      # - name: 🌐 Run tests
      #   run: flutter test
