name: Build Flutter Windows App

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Flutter (make sure you specify a stable channel or a specific version if needed)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'  # or specify a specific version
          channel: 'stable'

      # Cache Flutter Dependencies
      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.packages
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      # Get Flutter Dependencies
      - name: Get Flutter Dependencies
        run: flutter pub get

      # Build Windows App
      - name: Build Windows App
        run: flutter build windows --release

      # Upload Build Artifact (optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/Release
