name: 📦 iOS TestFlight Release

on:
  push:
    branches:
      - test/workflow
      #- develop
      #- release/*
      #- hotfix/*

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      XCODE_VERSION: 16.2

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📶 Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: 📦 Install Flutter dependencies
        run: flutter pub get

      - name: 🔐 Decode App Store Connect API key (.p8)
        run: echo "$APP_STORE_API_KEY" | base64 --decode > ios/AuthKey.p8
        env:
          APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}

      - name: 🧵 Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      - name: 🚀 Build and upload to TestFlight
        run: |
          cd ios
          fastlane ci_testflight_release
        env:
          FASTLANE_VERBOSE: 1
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
